import { Injectable, BadRequestException, NotFoundException, Logger } from '@nestjs/common';
import { PrismaService } from '@/prisma/prisma.service';
import { PaymentMethod, TransactionStatus, BookingStatus, PaymentStatus } from '@prisma/client';
import { CheckoutDto } from './dto/checkout.dto';
import { WalletService } from '../wallet/wallet.service';
import { TicketsService } from '../tickets/tickets.service';
import { ERROR_CODES, getErrorMessage } from '@/common/constants/error-codes.constant';

@Injectable()
export class PaymentsService {
  private readonly logger = new Logger(PaymentsService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly walletService: WalletService,
    private readonly ticketsService: TicketsService,
  ) {}

  async checkout(userId: number, checkoutDto: CheckoutDto) {
    const booking = await this.prisma.booking.findFirst({
      where: {
        bookingCode: checkoutDto.bookingCode,
        userId,
        status: BookingStatus.PENDING,
        paymentStatus: PaymentStatus.UNPAID,
      },
      include: {
        items: { include: { ticket: true } },
      },
    });

    if (!booking) {
      throw new NotFoundException({
        code: ERROR_CODES.BOOKING_001,
        message: getErrorMessage(ERROR_CODES.BOOKING_001),
      });
    }

    const amount = Number(booking.finalAmount);

    // Handle wallet payment
    if (checkoutDto.paymentMethod === PaymentMethod.WALLET) {
      return this.processWalletPayment(userId, booking.id, amount, booking.bookingCode);
    }

    // For external payment gateways, create pending transaction
    const transaction = await this.prisma.transaction.create({
      data: {
        bookingId: booking.id,
        userId,
        paymentMethod: checkoutDto.paymentMethod,
        amount,
        status: TransactionStatus.PENDING,
      },
    });

    // In a real implementation, this would redirect to payment gateway
    return {
      transactionId: transaction.id,
      bookingCode: booking.bookingCode,
      amount,
      paymentMethod: checkoutDto.paymentMethod,
      message: 'Vui lòng hoàn tất thanh toán.',
      // paymentUrl: would be generated by payment gateway
    };
  }

  private async processWalletPayment(
    userId: number,
    bookingId: number,
    amount: number,
    bookingCode: string,
  ) {
    await this.walletService.deductBalance(userId, amount, bookingCode);

    await this.prisma.$transaction(async (tx) => {
      // Create transaction record
      await tx.transaction.create({
        data: {
          bookingId,
          userId,
          paymentMethod: PaymentMethod.WALLET,
          amount,
          status: TransactionStatus.SUCCESS,
          payTime: new Date(),
        },
      });

      // Update booking status
      await tx.booking.update({
        where: { id: bookingId },
        data: {
          status: BookingStatus.CONFIRMED,
          paymentStatus: PaymentStatus.PAID,
        },
      });

      // Mark tickets as sold
      const ticketItems = await tx.bookingItem.findMany({
        where: { bookingId, itemType: 'SHOW_TICKET' },
      });

      const ticketIds = ticketItems.filter((i) => i.ticketId).map((i) => i.ticketId as number);
      if (ticketIds.length > 0) {
        await this.ticketsService.markTicketsAsSold(ticketIds, bookingId);
      }

      // Update tour booked count
      const tourItems = await tx.bookingItem.findMany({
        where: { bookingId, itemType: 'TOUR_SLOT' },
      });

      for (const item of tourItems) {
        if (item.tourScheduleId) {
          await tx.tourSchedule.update({
            where: { id: item.tourScheduleId },
            data: { bookedCount: { increment: item.quantity } },
          });
        }
      }
    });

    return {
      bookingCode,
      status: 'PAID',
      message: 'Thanh toán thành công!',
    };
  }

  async handleWebhook(gateway: string, payload: Record<string, unknown>) {
    this.logger.log(`Received webhook from ${gateway}`, JSON.stringify(payload));

    // In a real implementation, verify webhook signature and process payment result
    // This is a placeholder for payment gateway integration

    return { received: true };
  }
}
